# Configurazione del broker MQTT Mosquitto.
#
# Avvio dalla radice del progetto:
#
#   & "C:\Program Files\Mosquitto\mosquitto.exe" -c "communication\broker\mqtt_broker.conf" -v
#
# L'opzione -c indica il file di configurazione da utilizzare.
# L'opzione -v abilita la visualizzazione dettagliata di connessioni e messaggi.

# Il broker ascolta sulla porta MQTT standard 1883 su tutte le interfacce IPv4
# del PC. In questo modo:
# - il programma del drone può collegarsi localmente tramite 127.0.0.1;
# - lo smartwatch può raggiungere il broker tramite l'interfaccia Ethernet
#   configurata sulla rete 192.168.1.0/24.
listener 1883 0.0.0.0

# Consente connessioni MQTT senza nome utente e password.
# Questa scelta è coerente con i client utilizzati nel progetto e presuppone
# che il broker sia eseguito esclusivamente sulla rete locale controllata.
allow_anonymous true
